name: Common Sense Criminal Defense
favicon: null
layout_spectrum: 0
typography_spectrum: 0.99902
title: Common Sense Criminal Defense
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aaa19a'
    - '#3f66ab'
    - '#717f80'
    - '#36535b'
    - '#c4ccce'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
