name: commonsensecriminaldefense
favicon: null
layout_spectrum: 0.46489900816231966
typography_spectrum: 0.06092793238349259
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.39084359095431864
  lightness: 0.8371398455929011
  saturation: 0.5196921972092241
  rhythmicContrast: 0.12990432512015104
purpose: []
