name: Common Sense Criminal Defense
favicon: null
layout_spectrum: 0.24951
typography_spectrum: 0
title: Common Sense Criminal Defense
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7c6a5c'
    - '#302023'
    - '#9f8a79'
    - '#cdba9c'
    - '#130709'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
