name: Common Sense Criminal Defense
favicon: null
layout_spectrum: 0.99706
typography_spectrum: 0
title: Common Sense Criminal Defense
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faf8f9'
    - '#000000'
    - '#5670c5'
    - '#b5000c'
    - '#d3995d'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
